### ISSUE TITLE
Exporting selected layers

### ISSUE THREAD

**Issue by Andonome** [mrpiggi/svg#50]
Is there any way to export selected layers from an Inkscape svg file?

**Comment by mrpiggi** [comment]
Well, this is obviously a question regarding Inkscape itself and not for package `svg` since it is only a convenient wrapper for the Inkscape export itself. As far as I know, this is currently not possible. Feel free to open a feature request at the Inkscape tracker: https://gitlab.com/inkscape/inkscape

**Comment by Andonome** [comment]
> $ inkscape presentation.svg -i layer1 -j -C --export-png=layer1.png

[Source](https://graphicdesign.stackexchange.com/questions/8021/how-to-batch-export-layers-of-inkscape-generated-svg-file-to-bitmap-for-sprites)

I've tested it on Inkscape 1.1.1, and  it's working. I just can't seem to pass the right arguments to inscape from LaTeX.

**Comment by mrpiggi** [comment]
Did you try to use something like `\includesvg[inkscapeopt=-i layer1]{...}` as mentioned in the manual?
